enum Stay {
    ONEDAY, 
    TWODAYS,
    THREEDAYS,
    FOURDAYS,
    FIVEDAYS,
    SIXDAYS,
    ONEWEEK,
    ONETOTWOWEEKS,
    TWOTOFOURWEEKS,
    ONETOTWOMONTHS,
    THREETOSIXMONTHS,
    SIXMONTHSTOYEAR,
    GREATERTHANONEYEAR
}
